language: node_js
node_js:
- node
- 7.5.0
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm run build
env:
  global:
  - secure: ptCajBliY6gQIRZnzFN+PTxTASZwZSQDO1eRF1uxZMTpgs/m/AvskCgJlfetX3mRKqu+DhiKKqlh9c5T7K05rRLywXXrzx5TWQV9p14fmIa5bFg5mso071D3jQXhuZQgb+bRPm32ZjUnGZa0aSK91AgroKnuIQFa5J34tIFCBSWFT41Wmi4phwn0iVKnAfy8WOecC6AK2jy+vB5Bh49QEcM0BMPpta8R7JczUBPB9IwH9gNLyYzDXCyV5AHH+cKwm9cgheIO1M4Rkkep5H3O42sgsUuHyDX4w8nLQIW6XK4WBeLELmgERz9nF+6hQrtrHpKCbRNVY/EaQ3+QnALQbFsUO6x9AoZEeaYWcVsYi1XZS2ZXdct+JAlVU2hgYjHjy4tpFEOphda/k+gGHcWYMzgkKZDY9qW15W0IhIjDbldim5yGB5YLkmLywY16kaHwZhNR2TtGOPPdux4giQ9hVKD/lTNFlVCLzR4cY3QhjnYkDXpzZ/xVBT/qfNJphXYOa7ZxtBsr9HE45ithyJFVvAY8j6FfXcnYouCxvt033iZ+PW1gu32dFLm8WfSQ2usw2MytrgOrzopw8wHwXZCZAVRyghK7p/Ck1m/gxSpa4OcEUATHsMB8KgTRSF6P7Ov+cpzJcghyFfpvT8kNmP+5fdbkdQFtuCOdNu72eIRsPh0=
  - secure: kaJAtiVsx+v3BuNrlzC+qriIWo+KkPOgwtpO9j8NSwI6COWJ35EBEGd+ynYXVjc+SNFmYuJjboSKoPnzELcESQ4r7ZbICSmV1QUT5Q2MqdnnQ2tRCloRD6LRu3qHLg5Ny4+OkE9UY99V2zYzFPX2zPYyuxVmy2mEywEiGqNJTmOBGPlL50zI5o3FG+vjMkTJXLJBF/Ws21Wl+yPOVM9Do9rUmQrhyeWuaa8qWp72sMYrbKI9YoHQkJD63fZc/hDayJVE+iKHNh+a2oJCw2laluG+o/Glofq2d5TBsFGFFdND7QuzwLgLwAxx5Wtmh47QAKZB1FRBo6KYX0apr/yyClYcts71ud33dpd8SpOnM6bgRIitXSDBT0UbtaL88mD5MUx8Xb/JScO76DAuimx7Veb3KsRm2zWeJhtC4C2msA/ok3QlSp9+O0Bfzk7YvPd1kaT1MtL4/xInFnjJHu5mo1wOIsAMYVfhPRhG7RRiMYvA6iPeObw0NGv3JfYKC6kw1+y0SkHSVv3KZ92BFykhCmOgByrO0ATnor+TGEyQVLbuRPYgs78ax3M+dsjd7mshX6IZK6jCsj6uhegFgMJLTXMkQs2aisMsrf4Z7IAKffHx/OCDPdZYoznIYuMJh04qcZjCvUZb1/xNVT/qryuE6/keCx2Ido0jC4kfF3S7yK0=
